{% set name = "perfmetrics" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/perfmetrics-{{ version }}.tar.gz
  sha256: 89c8b37be7f945a5eefb8f3748a3ed90472c267574ecbe7388a7e930bbd2621a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - perfmetrics
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zodb/perfmetrics
  summary: Send performance metrics about Python code to Statsd
  license: BSD-3-Clause-Modification
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
