{% set name = "perfmetrics" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/perfmetrics-{{ version }}.tar.gz
  sha256: 495e0eee5681961ec8b2fce9eafa372c90919d9a57cbe7ca0fca7b52a89f5519

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - perfmetrics
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zodb/perfmetrics
  summary: Send performance metrics about Python code to Statsd
  license: BSD-3-Clause-Modification
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
