{% set name = "perfmetrics" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/perfmetrics-{{ version }}.tar.gz
  sha256: 3a86e0f7b6b793722fdbb56813fa7f849385431dc065c283845cb1356cfea3ff

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - perfmetrics
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zodb/perfmetrics
  summary: Send performance metrics about Python code to Statsd
  license: BSD-3-Clause-Modification
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
