{% set name = "perfmetrics" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/perfmetrics-{{ version }}.tar.gz
  sha256: f6da36006cfef7d2cb9f938da369cd2fbdd40b9c6025ac645854c7ee72fe479f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - perfmetrics
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zodb/perfmetrics
  summary: Send performance metrics about Python code to Statsd
  license: BSD-3-Clause-Modification
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
